version: '3.8'

services:
  mysql_container:
    image: mysql:8
    restart: always
    env_file: backend/.env
    volumes:
      - ./mysql-volume:/var/lib/mysql

  fastapi_container:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_container
    ports:
      - "3000:8000" # 3000 포트 open
    env_file: backend/.env
    # 60초간 mysql_container 실행 대기하고, 이후에 api 서버 실행
    command: [ "poetry","run","wait-for-it","--timeout=60","--service=mysql_container:3306","--","poetry","run","python","backend/main.py" ]
